# Generated by Django 2.2.7 on 2019-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0002_auto_20191121_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videotitle',
            field=models.CharField(max_length=20),
        ),
    ]
